EVENTBRITE_APP_KEY: N6PAMASE3CEHE6UTY2RXZOHWMV66ROZ6MJOQQ5SFW5OPP3NHN4
EVENTBRITE_USER_KEY: QED3NHRTNVR6V5MFQQ54
EVENTBRITE_EVENT_ID: 13148891689
EVENTBRITE_ATTENDEES_DISPLAY_NUMBER: 10
DISPLAYED_TEAM_MEMBERS: 4
AWS_BUCKET: "ouisharefest"
AWS_KEY: "AKIAJPUIA5CLQHACUKQA"
AWS_SECRET: "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"