EVENTBRITE_APP_KEY: N6PAMASE3CEHE6UTY2RXZOHWMV66ROZ6MJOQQ5SFW5OPP3NHN4
EVENTBRITE_USER_KEY: QED3NHRTNVR6V5MFQQ54
EVENTBRITE_EVENT_ID: 13148891689
EVENTBRITE_ATTENDEES_DISPLAY_NUMBER: 10
DISPLAYED_TEAM_MEMBERS: 4
AWS_BUCKET: "pitchme-rails-backbone"
AWS_KEY: "AKIAJ3CEPDOTIX6ETIGQ"
AWS_SECRET: "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"