# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

COMPANY_LONG: 2.36378
COMPANY_LAT: 48.86993

AWS_BUCKET: "pitchme-rails-backbone"
AWS_KEY: "AKIAJ3CEPDOTIX6ETIGQ"
AWS_SECRET: "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"

MAILER_SMTP_ADDRESS: "smtp.webfaction.com"
MAILER_DOMAIN: "ouishare.webfactional.com"
MAILER_USERNAME: "ouisharefest"
MAILER_PASSWORD: "(7cmo562$318"

DISPLAYED_SPEAKERS: 8
DISPLAYED_TEAM_MEMBERS: 4

GA_CREDENTIALS: "UA-37109643-1"

#/// EventBrite ///

# 2014
# EVENTBRITE_APP_KEY: 'IWKXO472LQBDZ5CUFU'
# EVENTBRITE_USER_KEY: '135664325248904524750'
# EVENTBRITE_EVENT_ID: "10108670305"

# 2015
EVENTBRITE_APP_KEY: N6PAMASE3CEHE6UTY2RXZOHWMV66ROZ6MJOQQ5SFW5OPP3NHN4
EVENTBRITE_USER_KEY: QED3NHRTNVR6V5MFQQ54
EVENTBRITE_EVENT_ID: 13148891689

EVENTBRITE_ATTENDEES_DISPLAY_NUMBER: 12

#/// Event Brite ///

OUISHARE_FEST_EVENT_YEAR: 2014

YAML_OUISHARE_FILE_PATH: 'config/locales/ouishare_en.yml'
YAML_INDIVIDUALS_FILE_PATH: 'config/locales/individuals_en.yml'

TRANSIFEX_BASE_URL: "https://www.transifex.com/api/2"
TRANSIFEX_OUISHARE_URL: "/project/ouishare/resource/ouishare_enyml/content"
TRANSIFEX_INDIVIDUALS_URL: "/project/ouishare/resource/individuals_enyml/content"

TRANSIFEX_CREDENTIAL_LOGIN: 'fredericgrais'
TRANSIFEX_CREDENTIAL_SECRET: 'futur123'

PATH_BIN: "~/webapps/ouishare_fest/bin/"