development:
  adapter: postgresql
  encoding: unicode
  database: pitchme-rails-backbone_development
  host: localhost
  username: postgres
  password: pitchme
  pool: 5
  timeout: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: pitchme-rails-backbone_test
  host: localhost
  username: postgres
  password: pitchme
  pool: 5
  timeout: 5432

#Webfaction database credentials

 
production:
  adapter: postgresql
  encoding: unicode
  database: ouishare_fest_production
  host: localhost
  username: pitchme
  password: pitchme
  pool: 5
  timeout: 5432
