require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MagazinesController do

  # This should return the minimal set of attributes required to create a valid
  # Magazine. As you add validations to Magazine, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MagazinesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all magazines as @magazines" do
      magazine = Magazine.create! valid_attributes
      get :index, {}, valid_session
      assigns(:magazines).should eq([magazine])
    end
  end

  describe "GET show" do
    it "assigns the requested magazine as @magazine" do
      magazine = Magazine.create! valid_attributes
      get :show, {:id => magazine.to_param}, valid_session
      assigns(:magazine).should eq(magazine)
    end
  end

  describe "GET new" do
    it "assigns a new magazine as @magazine" do
      get :new, {}, valid_session
      assigns(:magazine).should be_a_new(Magazine)
    end
  end

  describe "GET edit" do
    it "assigns the requested magazine as @magazine" do
      magazine = Magazine.create! valid_attributes
      get :edit, {:id => magazine.to_param}, valid_session
      assigns(:magazine).should eq(magazine)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Magazine" do
        expect {
          post :create, {:magazine => valid_attributes}, valid_session
        }.to change(Magazine, :count).by(1)
      end

      it "assigns a newly created magazine as @magazine" do
        post :create, {:magazine => valid_attributes}, valid_session
        assigns(:magazine).should be_a(Magazine)
        assigns(:magazine).should be_persisted
      end

      it "redirects to the created magazine" do
        post :create, {:magazine => valid_attributes}, valid_session
        response.should redirect_to(Magazine.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved magazine as @magazine" do
        # Trigger the behavior that occurs when invalid params are submitted
        Magazine.any_instance.stub(:save).and_return(false)
        post :create, {:magazine => {  }}, valid_session
        assigns(:magazine).should be_a_new(Magazine)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Magazine.any_instance.stub(:save).and_return(false)
        post :create, {:magazine => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested magazine" do
        magazine = Magazine.create! valid_attributes
        # Assuming there are no other magazines in the database, this
        # specifies that the Magazine created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Magazine.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => magazine.to_param, :magazine => { "these" => "params" }}, valid_session
      end

      it "assigns the requested magazine as @magazine" do
        magazine = Magazine.create! valid_attributes
        put :update, {:id => magazine.to_param, :magazine => valid_attributes}, valid_session
        assigns(:magazine).should eq(magazine)
      end

      it "redirects to the magazine" do
        magazine = Magazine.create! valid_attributes
        put :update, {:id => magazine.to_param, :magazine => valid_attributes}, valid_session
        response.should redirect_to(magazine)
      end
    end

    describe "with invalid params" do
      it "assigns the magazine as @magazine" do
        magazine = Magazine.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Magazine.any_instance.stub(:save).and_return(false)
        put :update, {:id => magazine.to_param, :magazine => {  }}, valid_session
        assigns(:magazine).should eq(magazine)
      end

      it "re-renders the 'edit' template" do
        magazine = Magazine.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Magazine.any_instance.stub(:save).and_return(false)
        put :update, {:id => magazine.to_param, :magazine => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested magazine" do
      magazine = Magazine.create! valid_attributes
      expect {
        delete :destroy, {:id => magazine.to_param}, valid_session
      }.to change(Magazine, :count).by(-1)
    end

    it "redirects to the magazines list" do
      magazine = Magazine.create! valid_attributes
      delete :destroy, {:id => magazine.to_param}, valid_session
      response.should redirect_to(magazines_url)
    end
  end

end
